:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - [tag_filters_0, 1]
  - [tag_filters_1, 1]
  - [tag_filters_2, 1]
  - [tag_filters_3, 1]
  - [tag_filters_4, 1]
  - [updater, 1]
  - [file_cache, 1]
  - [importer, 1]
